# CultivApp - Base Spring Boot Configuration
# This file contains default settings shared across all environments

spring:
  application:
    name: cultivapp

  # Active profile determines which environment-specific config to load
  # dev = development (file-based H2)
  # prod = production (PostgreSQL)
  profiles:
    active: dev

  # JPA/Hibernate settings
  jpa:
    # Show SQL queries in console (useful for debugging)
    show-sql: false
    # Format SQL for readability
    properties:
      hibernate:
        format_sql: true
    # Open EntityManager in view pattern for lazy loading
    open-in-view: false

# Server configuration
server:
  port: 8080
  error:
    # Include error messages in API responses
    include-message: always
    include-binding-errors: always

# JWT Security settings
security:
  jwt:
    # Secret key for signing JWT tokens (override in production!)
    secret: cultivapp-dev-secret-please-change-32-bytes-min
    # Token expiration time in minutes
    exp-minutes: 120
